// Mock Data Utilities
export const mockPredictionsHistory = [
  {
    id: 1,
    date: '2026-05-14',
    time: '14:30',
    status: 'Early Stage Parkinson\'s',
    confidence: 87,
    severity: 'Early',
    updrs: 15,
    risk: 'Moderate',
    statusColor: '#f59e0b',
  },
  {
    id: 2,
    date: '2026-04-20',
    time: '10:15',
    status: 'Healthy',
    confidence: 92,
    severity: 'N/A',
    updrs: 0,
    risk: 'Low',
    statusColor: '#10b981',
  },
  {
    id: 3,
    date: '2026-03-10',
    time: '09:45',
    status: 'Moderate Parkinson\'s',
    confidence: 89,
    severity: 'Moderate',
    updrs: 35,
    risk: 'High',
    statusColor: '#ef4444',
  },
  {
    id: 4,
    date: '2026-02-25',
    time: '16:20',
    status: 'Healthy',
    confidence: 94,
    severity: 'N/A',
    updrs: 0,
    risk: 'Low',
    statusColor: '#10b981',
  },
  {
    id: 5,
    date: '2026-01-15',
    time: '11:00',
    status: 'Early Stage Parkinson\'s',
    confidence: 85,
    severity: 'Early',
    updrs: 12,
    risk: 'Moderate',
    statusColor: '#f59e0b',
  },
];

export const mockPatientProfiles = [
  {
    id: 1,
    name: 'Ahmed Khan',
    age: 52,
    email: 'ahmed.khan@email.com',
    phone: '+92-300-1234567',
    lastAnalysis: '2026-05-14',
    totalAnalyses: 8,
    riskStatus: 'Moderate',
  },
  {
    id: 2,
    name: 'Fatima Ali',
    age: 48,
    email: 'fatima.ali@email.com',
    phone: '+92-300-7654321',
    lastAnalysis: '2026-05-12',
    totalAnalyses: 12,
    riskStatus: 'Low',
  },
  {
    id: 3,
    name: 'Hassan Raza',
    age: 65,
    email: 'hassan.raza@email.com',
    phone: '+92-300-9876543',
    lastAnalysis: '2026-05-10',
    totalAnalyses: 15,
    riskStatus: 'High',
  },
  {
    id: 4,
    name: 'Ayesha Malik',
    age: 55,
    email: 'ayesha.malik@email.com',
    phone: '+92-300-5555555',
    lastAnalysis: '2026-05-08',
    totalAnalyses: 10,
    riskStatus: 'Moderate',
  },
  {
    id: 5,
    name: 'Ali Hassan',
    age: 60,
    email: 'ali.hassan@email.com',
    phone: '+92-300-1111111',
    lastAnalysis: '2026-05-06',
    totalAnalyses: 6,
    riskStatus: 'Low',
  },
];

export const mockAnalyticsDashboard = {
  totalPatients: 234,
  totalAnalyses: 1250,
  averageConfidence: 88.5,
  severityDistribution: [
    { status: 'Healthy', count: 450, percentage: 36 },
    { status: 'Early Stage', count: 385, percentage: 31 },
    { status: 'Moderate', count: 280, percentage: 22 },
    { status: 'Severe', count: 135, percentage: 11 },
  ],
  riskDistribution: [
    { risk: 'Low', count: 450, percentage: 36 },
    { risk: 'Moderate', count: 500, percentage: 40 },
    { risk: 'High', count: 300, percentage: 24 },
  ],
};

export const mockDoctorDashboard = {
  myPatients: 45,
  activeAnalyses: 8,
  pendingReviews: 5,
  reportsPending: 3,
  criticalCases: 2,
};

export const generateMockFullReport = (prediction) => {
  return `
PARKINSON'S DISEASE DETECTION REPORT
Generated: ${new Date().toLocaleString()}

PATIENT INFORMATION
-------------------
Test Date: ${new Date().toISOString().split('T')[0]}
Analysis Type: Voice-based AI Analysis
Recording Duration: 1:45 minutes
Analysis Status: Completed Successfully

PREDICTION RESULTS
------------------
Status: ${prediction.status}
Confidence Level: ${prediction.confidence}%
Severity Level: ${prediction.severity || 'N/A'}
UPDRS Score: ${prediction.updrs}
Risk Level: ${prediction.risk}

VOICE ANALYSIS METRICS
----------------------
Jitter: 1.2% (Normal: < 1.04%)
Shimmer: 3.4% (Normal: < 3.81%)
HNR (Harmonics-to-Noise Ratio): 21.3 dB (Normal: > 20 dB)
MFCC (Mel-Frequency Cepstral Coefficients): 42 coefficients
Pitch Frequency: 145 Hz
Recording Quality: Excellent

CLINICAL INTERPRETATION
-----------------------
${prediction.recommendation}

RECOMMENDATIONS
---------------
1. Consult with a qualified neurologist for professional evaluation
2. Schedule follow-up analysis in 3-6 months
3. Maintain voice recording hygiene for accurate future tests
4. Keep this report for medical records

TECHNICAL DETAILS
-----------------
AI Model: Multi-level Hierarchical Classifier v2.1
Feature Set: 150+ Acoustic Features
Processing Time: 14.2 seconds
Data Quality Score: 95%

DISCLAIMER
----------
This report is for informational purposes only and should not be used as a standalone diagnostic tool. 
A qualified medical professional must conduct proper clinical evaluation and examinations for diagnosis confirmation.

Generated by NeuroVoice AI Analysis System
  `;
};

export const mockUserData = {
  id: 'USR-001',
  name: 'Test User',
  email: 'user@example.com',
  age: 50,
  gender: 'Male',
  createdAt: '2026-01-15',
};
